FROM alpine:3.3

RUN set -x                  && \
    apk --update upgrade    && \
    apk add ca-certificates && \
    rm -rf /var/cache/apk/*

RUN set -x && \
    wget -O /kubectl \
      https://storage.googleapis.com/kubernetes-release/release/$(wget -q -O - https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x /kubectl

ENTRYPOINT ["/kubectl"]
